# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Install system dependencies including LibreOffice and Korean fonts
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libffi-dev \
    libreoffice-impress \
    fonts-noto-cjk \
    fonts-noto-cjk-extra \
    fonts-nanum \
    fonts-unfonts-core \
    fontconfig \
    && rm -rf /var/lib/apt/lists/* \
    && fc-cache -f -v

# Set work directory
WORKDIR /app

# Copy the application code
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port if needed (not needed for stdio)

# Set the entrypoint to run the MCP server
ENTRYPOINT ["python", "ppt_mcp_server.py"]
